import type { PropsWithChildren } from 'react';
import type { Metadata } from 'next';
import { Flex, Heading } from '@chakra-ui/react';

import { Providers } from './providers';

export const metadata: Metadata = {
  title: '1Password share link to URL scheme Example',
  description: 'Generated by HardFury',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang='en'>
      <body>
        <Providers>
          <Flex alignItems='center' h={16} px={4} border='1px' borderColor='gray.200'>
            <Heading as='h5' size='sm'>
              1Password share link to URL scheme
            </Heading>
          </Flex>

          {children}
        </Providers>
      </body>
    </html>
  );
}
